# making hometasks
CFLAGS = -pedantic -Wall
CFLAGS1 = -pthread
all:
	gcc forks.c -o  ht17_treads.out $(CFLAGS) 
	gcc threads.c -o  2.out $(CFLAGS) $(CFLAGS1)
	gcc signals.c -o  ht17_signals.out $(CFLAGS1) $(CFLAGS)	
	@echo "to remove *.out use clean"
clean:
	rm -f 2.out
	rm -f ht17_treads.out
	rm -f ht17_signals.out
	@echo "all clean"



	

